### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by designomatt** [sarperdag/SESpringBoard#1]
What type of licensing does this have?

**Comment by sarperdag** [comment]
Haven't decided yet, still learning about different licenses. I want it to be freely usable for any commercial or personal use with references to the initial developer. Which one would suit this best you think?

Sent from my iPhone

Sarp Erdag

**Comment by designomatt** [comment]
Not sure…I would look at other code libraries you admire here and compare them to your needs. Some of the libraries I use most here have the BSD open source license; that might be appropriate but ultimately is up to your guidance.

**Comment by sarperdag** [comment]
Added MIT license
