### ISSUE TITLE
need to subclass

### ISSUE THREAD

**Issue by JanC** [sarperdag/SESpringBoard#10]
Hi,
a big inconvenient is the fact that a user has to subclass the SEViewController. How is one supposed to present controllers that cannot subclass the SEViewController? e.g. controllers from other libraries that I cannot modify or just don't want to make depended on SESpringBoard?

cheers

**Comment by sarperdag** [comment]
You are right. I have plans to work on this but can't find time these days :) I'd really appreciate if you come up with ideas, fork and implement it yourself.

**Comment by JanC** [comment]
all right, I'll have a look on it ... when I have time :)

**Comment by JanC** [comment]
ok I think I have a simple solution using categories. I will fork it

**Comment by JanC** [comment]
did you have a look at this?
