### ISSUE TITLE
toolbar not sticking

### ISSUE THREAD

**Issue by justausername** [sarperdag/SESpringBoard#2]
I noticed that some UI elements like the toolbar won't stick. Try  adding one in the ChildViewController viewDidLoad method run the example and open up any view twice.
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // Do any additional setup after loading the view from its nib.
  
  UIBarButtonItem  *buttonItemDoSomething = [[[ UIBarButtonItem alloc ] initWithTitle: @"DoSomething" style:    UIBarButtonItemStyleBordered target:self action: @selector(onCreate:) ] autorelease];
  
  NSArray *toolBarItems = [[[NSArray alloc] buttonItemDoSomething, nil] autorelease];
  
  [self.navigationController setToolbarHidden:NO];
  
  self.toolbarItems =  toolBarItems;
  }

**Comment by sarperdag** [comment]
Let me try it and I will get back to you in about 24 hrs.

**Comment by justausername** [comment]
I also noticed that many of the view's life cycle methods like viewWillAppear and viewDidAppear are not called the first time the view cycles through. They are called called on subsequent view loads but then the viewDidLoad is not called again . I am also trying to figure out what is going on. I will try again tonight.

**Comment by sarperdag** [comment]
You are right, I reproduced the issue. Now working on a fix.

**Comment by sarperdag** [comment]
OK it looks like we have to manually call the view did appear methods for the navigation controller and the child viewcontrollers for versions lower than iOS5. Commited the fix, now it should be working.
